package it.barcaioli.webserver.user;

import java.util.Optional;

import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service //A @Component more specific
public class UserService {

	private final UserData userData;

	public UserService(UserData user){
    	this.userData = user;
    }

	public Iterable<User> getCustomers() {
    	//findAll() it's auto generated by SpringBoot
        return userData.findAll();
    }
    
	public User getCustomer(Long id) {
    	//findById() it's auto generated by SpringBoot
		Optional<User> user = userData.findById(id);
		
		if (!user.isPresent())
			throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Customer doesn't exist");
		
		return user.get();
    }
	
	private User getCustomerByEmail(String email) {
		Iterable<User> users = userData.findAll();
		 
        for (User user : users) {
            if (user.getEmail().equalsIgnoreCase(email)) {
            	return user;
            }
        }
        return null;
	}

	public User signUp(User newCustomer) {
		User user = getCustomerByEmail(newCustomer.getEmail());
		
		if (user!=null)
			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Customer already exists");
		
		//Hash the password for the first time, with a randomly-generated salt
		String hashed = BCrypt.hashpw(newCustomer.getPassword(), BCrypt.gensalt());
		newCustomer.setPassword(hashed);
		
		return userData.save(newCustomer);
    }
	
	public User login(User logginCustomer) {
		
		User user = getCustomerByEmail(logginCustomer.getEmail());
		
		if (user==null)
			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Customer email not found");
		
    	if (BCrypt.checkpw(logginCustomer.getPassword(), user.getPassword())) {
    		if (user.isLoggedIn()) {
    			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "User is already logged in");
    		}
    		user.setLoggedIn(true);
            return userData.save(user);
        } else {
        	throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Password not correct");
        }
	}
	
	public User logout(User logginOutCustomer) {
		User user = getCustomerByEmail(logginOutCustomer.getEmail());
		
		if (user==null)
			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Customer email not found");
		
    	if (user.isLoggedIn()){
    		user.setLoggedIn(false);
            return userData.save(user);
        } else {
        	throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "User is not logged in");
        }
	}

	public void deleteCustomer(Long id) {
		Optional<User> userToDelete = userData.findById(id);
		
		if (!userToDelete.isPresent())
			throw new ResponseStatusException(HttpStatus.NOT_FOUND, "No user to delete");
		
        //delete() it's auto generated by SpringBoot
        userData.delete(userToDelete.get());
    }
}
