package it.barcaioli.webserver.boat;

import org.springframework.stereotype.Service;

@Service //A @Component more specific
public class BoatService {

	private final BoatData boatData;

	public BoatService(BoatData boat){
    	this.boatData = boat;
    }

	public Iterable<Boat> getBoats() {
    	//findAll() it's auto generated by SpringBoot
        return boatData.findAll();
    }
    
	public Boat getBoat(Long id) {
    	//findById() it's auto generated by SpringBoot
        return boatData.findById(id).orElseThrow();
    }

	public Boat createBoat(Boat newBoat) {
		//save() it's auto generated by SpringBoot
        return boatData.save(newBoat);
    }
    
	public Boat updateBoat(Long id, Boat boat) {
        Boat boatToUpdate = boatData.findById(id).orElseThrow();
        boatToUpdate.setModel(boat.getModel());
        boatToUpdate.setNumSeats(boat.getNumSeats());
        return boatData.save(boatToUpdate);
    }

	public void deleteBoat(Long id) {
        Boat boatToDelete = boatData.findById(id).orElseThrow();
        //delete() it's auto generated by SpringBoot
        boatData.delete(boatToDelete);
    }
}
