package it.barcaioli.webserver.trip;

import org.springframework.stereotype.Service;

@Service //A @Component more specific
public class TripService {

	private final TripData tripData;

	public TripService(TripData trip){
    	this.tripData = trip;
    }

	public Iterable<Trip> getTrips() {
    	//findAll() it's auto generated by SpringBoot
        return tripData.findAll();
    }
    
	public Trip getTrip(Long id) {
    	//findById() it's auto generated by SpringBoot
        return tripData.findById(id).orElseThrow();
    }

	public Trip createTrip(Trip newTrip) {
		//save() it's auto generated by SpringBoot
        return tripData.save(newTrip);
    }
    
	public Trip updateTrip(Long id, Trip trip) {
        Trip tripToUpdate = tripData.findById(id).orElseThrow();
        tripToUpdate.setDateTime(trip.getDateTime());
        return tripData.save(tripToUpdate);
    }

	public void deleteTrip(Long id) {
        Trip tripToDelete = tripData.findById(id).orElseThrow();
        //delete() it's auto generated by SpringBoot
        tripData.delete(tripToDelete);
    }
}
