package it.barcaioli.webserver.trip;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service // A @Component more specific
public class TripService {

	@Autowired
	private final TripRepository tripRepository;

	public TripService(TripRepository trip) {
		this.tripRepository = trip;
	}

	public List<Trip> getTrips() {
		// findAll() it's auto generated by SpringBoot
		return tripRepository.findAll(Sort.by(Sort.Direction.ASC, "id"));
	}

	public Trip getTrip(Long id) {
		// findById() it's auto generated by SpringBoot
		Optional<Trip> trip = tripRepository.findById(id);

		if (!trip.isPresent())
			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Trip doesn't exist");

		return trip.get();
	}

	public Trip createTrip(Trip newTrip) {
		// save() it's auto generated by SpringBoot
		return tripRepository.save(newTrip);
	}

	public Trip updateTrip(Long id, Trip trip) {
		Optional<Trip> tripToUpdate = tripRepository.findById(id);

		if (!tripToUpdate.isPresent())
			throw new ResponseStatusException(HttpStatus.NOT_FOUND, "No trip to update");

		Trip tripFound = tripToUpdate.get();

		tripFound.setDateTime(trip.getDateTime());
		return tripRepository.save(tripFound);
	}

	public void deleteTrip(Long id) {
		Optional<Trip> tripToDelete = tripRepository.findById(id);

		if (!tripToDelete.isPresent())
			throw new ResponseStatusException(HttpStatus.NOT_FOUND, "No trip to delete");

		// delete() it's auto generated by SpringBoot
		tripRepository.delete(tripToDelete.get());
	}
}
